import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import authServerApiSidebar from './docs/api/auth-server/sidebar';
import resourceApiApiSidebar from './docs/api/resource-api/sidebar';

const sidebars: SidebarsConfig = {
  // Main docs sidebar. Listed explicitly so the generated API docs under
  // docs/api/ don't get pulled in here as well.
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        description:
          'How the prototype is put together.',
      },
      items: ['architecture/overview'],
    },
    {
      type: 'category',
      label: 'Services',
      link: {
        type: 'generated-index',
        description: 'The services that make up the prototype.',
      },
      items: [
        'services/auth-server',
        'services/resource-api',
        'services/nginx',
        'services/web',
      ],
    },
    'local-development',
    'deploying-to-aws',
    'troubleshooting',
  ],

  // Per-spec API sidebars generated by docusaurus-plugin-openapi-docs.
  authServerSidebar: authServerApiSidebar,
  resourceApiSidebar: resourceApiApiSidebar,
};

export default sidebars;
